-- Generated by sqrrl. Review before applying; preserve migration history.

CREATE TABLE "settings" (
  "user_id" INTEGER NOT NULL,
  "key" TEXT NOT NULL,
  "value" TEXT,
  PRIMARY KEY ("user_id", "key"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "tasks" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "owner_id" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)),
  FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE
) STRICT;

CREATE INDEX "tasks_owner_idx" ON "tasks" ("owner_id");

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT UNIQUE
) STRICT;
