from os import replace
from pathlib import Path
from pprint import pformat
from typing import Optional
from sqrrl.errors import SqrrlError
from tempfile import NamedTemporaryFile
from sqrrl.schema import Field, Schema, Table

_HEADER = "# Code generated by sqrrl. DO NOT EDIT.\n"
_TYPES = {"integer": "int", "text": "str", "boolean": "bool", "real": "float", "blob": "bytes"}

def _type(field: Field, *, scoped: bool = False) -> str:
    prefix = "_" if scoped else ""
    name = prefix + _TYPES[field.kind]

    return f"{prefix}Optional[{name}]" if field.is_nullable else name

def _arguments(table: Table, update: bool) -> list[str]:
    arguments = []
    for field in table.fields:
        if update and (field in table.keys or field.is_immutable):
            continue

        generated = table.auto_key and field in table.keys
        optional = update or generated or field.is_nullable or field.default_sql is not None
        annotation = _type(field)
        arguments.append(f"{field.name}: {annotation} | Unset = UNSET" if optional else f"{field.name}: {annotation}")

    return arguments

def _values(table: Table, update: bool) -> str:
    fields = (field for field in table.fields if not update or (field not in table.keys and not field.is_immutable))

    return "{" + ", ".join(f"{field.name!r}: {field.name}" for field in fields) + "}"

def _compact_metadata(value: object) -> object:
    """Omit default metadata values to keep generated modules small."""
    if isinstance(value, dict):
        return {
            key: _compact_metadata(item)
            for key, item in value.items()
            if item not in (None, False, "", (), []) and not (key == "key" and item == value.get("name"))
        }

    if isinstance(value, (tuple, list)):
        return tuple(_compact_metadata(item) for item in value)

    return value

def render(schema: Schema) -> str:
    """Generate typed async repositories without importing application code at runtime."""
    normalized = schema.normalize()
    if not normalized.tables:
        raise SqrrlError("At least one table is required for generation")

    kinds = sorted({field.kind for table in normalized.tables for field in table.fields})
    nullable = any(field.is_nullable for table in normalized.tables for field in table.fields)
    decoders = [f"decode_{kind}" for kind in kinds]
    if nullable:
        decoders.append("decode_nullable")

    imports = [
        "from sqlite3 import Row",
        "from typing import AsyncIterator" + (", Optional, Optional as _Optional" if nullable else ""),
        "from dataclasses import dataclass",
        "from contextlib import asynccontextmanager",
        "from sqrrl.schema import Schema",
        "from sqrrl.runtime import UNSET, Column as _Column, Database, Repository, Unset",
        "from sqrrl.runtime import " + ", ".join(decoders),
        "from builtins import " + ", ".join(f"{_TYPES[kind]} as _{_TYPES[kind]}" for kind in kinds),
    ]
    lines = [
        _HEADER.rstrip(),
        "# fmt: off",
        *sorted(imports, key=lambda line: (len(line), line)),
        "",
    ]
    for table in normalized.tables:
        lines.extend(["", "@dataclass(frozen=True, slots=True, kw_only=True)", f"class {table.model}:"])
        lines.extend(f"    {field.name}: {_type(field, scoped=True)}" for field in table.fields)
        if len(table.keys) > 1:
            lines.extend(["", "", "@dataclass(frozen=True, slots=True, kw_only=True)", f"class {table.model}Key:"])
            lines.extend(f"    {field.name}: {_type(field, scoped=True)}" for field in table.keys)

    lines.extend(
            [
                "",
                "",
                "_SCHEMA = Schema.from_dict("
                + pformat(_compact_metadata(normalized.to_dict()), width=100, sort_dicts=True)
                + ")",
            ]
    )
    for index, table in enumerate(normalized.tables):
        lines.extend(["", "", f"def _decode_{table.name}(row: Row) -> {table.model}:", f"    return {table.model}("])
        for field in table.fields:
            decoder = f"decode_{field.kind}"
            value = (
                f"decode_nullable(row[{field.name!r}], {decoder})"
                if field.is_nullable
                else f"{decoder}(row[{field.name!r}])"
            )
            lines.append(f"        {field.name}={value},")

        lines.extend(
                [
                    "    )",
                    "",
                    "",
                    f"_model_{table.model} = {table.model}",
                    "",
                    "",
                    "@dataclass(frozen=True)",
                    f"class _{table.model}Columns:",
                ]
        )
        lines.extend(
                f"    {field.name}: _Column[_model_{table.model}, {_type(field, scoped=True)}] = _Column(_model_{table.model}, _SCHEMA.tables[{index}].field({field.name!r}))"
                for field in table.fields
        )
        lines.extend(
                [
                    "",
                    "",
                    f"{table.model}Columns = _{table.model}Columns()",
                    "",
                    "",
                    f"class {table.model}Repository(Repository[{table.model}]):",
                    "    def __init__(_self, database: Database) -> None:",
                    f"        Repository.__init__(_self, database, _SCHEMA.tables[{index}], {table.model}, _decode_{table.name})",
                ]
        )
        keys = table.keys
        if not keys:
            raise SqrrlError(f"{table.name} has no primary key")

        key_type = _type(keys[0]) if len(keys) == 1 else f"{table.model}Key"
        key = "(" + ", ".join(f"_key.{field.name}" for field in keys) + ",)" if len(keys) > 1 else "(_key,)"
        lines.extend(
                [
                    "",
                    f"    async def get(_self, _key: {key_type}, /) -> {table.model}:",
                    f"        return await _self._get({key})",
                ]
        )
        create_arguments = ", ".join(_arguments(table, False))
        lines.extend(
                [
                    "",
                    f"    async def create(_self, *, {create_arguments}) -> {table.model}:",
                    f"        return await _self._insert({_values(table, False)})",
                ]
        )
        update_arguments = _arguments(table, True)
        suffix = ", *, " + ", ".join(update_arguments) if update_arguments else ""
        lines.extend(
                [
                    "",
                    f"    async def update(_self, _key: {key_type}, /{suffix}) -> {table.model}:",
                    f"        return await _self._update({key}, {_values(table, True)})",
                ]
        )
        lines.extend(
                ["", f"    async def delete(_self, _key: {key_type}, /) -> None:",
                 f"        await _self._delete({key})"]
        )

    lines.extend(
            [
                "",
                "",
                "class Client:",
                "    def __init__(self, database: Database) -> None:",
                "        self.database = database",
            ]
    )
    lines.extend(f"        self.{table.name} = {table.model}Repository(database)" for table in normalized.tables)
    lines.extend(
            [
                "",
                "    @asynccontextmanager",
                "    async def transaction(self) -> AsyncIterator[Client]:",
                "        async with self.database.transaction():",
                "            yield Client(self.database)",
                "",
            ]
    )
    source = "\n".join(lines)
    compile(source, "sqrrl_generated.py", "exec")

    return source

def write(path: str | Path, schema: Schema, *, check: bool = False) -> Path:
    target = Path(path)
    source = render(schema)
    try:
        existing: Optional[str] = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    if existing == source:
        return target

    if check:
        raise SqrrlError(f"{target} is missing or stale; run sqrrl generate")

    if existing is not None and not existing.startswith(_HEADER):
        raise SqrrlError(f"Refusing to overwrite handwritten file {target}")

    target.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile(
            mode="w", encoding="utf-8", newline="\n", dir=target.parent, suffix=".tmp", delete=False
    ) as temporary:
        temporary_path = Path(temporary.name)
        try:
            temporary.write(source)
        except BaseException:
            temporary.close()
            temporary_path.unlink(missing_ok=True)
            raise

    try:
        replace(temporary_path, target)
    finally:
        temporary_path.unlink(missing_ok=True)

    return target
