from os import replace
from pathlib import Path
from pprint import pformat
from typing import Optional
from sqrrl.errors import SqrrlError
from tempfile import NamedTemporaryFile
from sqrrl.schema import Field, Schema, Table

_HEADER = "# Code generated by sqrrl. DO NOT EDIT.\n"
_TYPES = {'integer': 'int', 'text': 'str', 'boolean': 'bool', 'real': 'float', 'blob': 'bytes',
          'datetime': 'datetime', 'json': 'JsonValue'}

def _type(field: Field, *, scoped: bool = False) -> str:
    prefix = "_" if scoped else ""
    name = _python_alias(field.python_type) if field.python_type else ('_' if field.kind in ('datetime', 'json') else prefix) + _TYPES[field.kind]

    return f"{prefix}Optional[{name}]" if field.is_nullable else name

def _python_alias(reference: str) -> str:
    return '_type_' + reference.replace('_', '_u').replace('.', '_d').replace(':', '_c')

def _arguments(table: Table, update: bool) -> list[str]:
    arguments = []
    for field in table.fields:
        if update and (field in table.keys or field.is_immutable):
            continue

        generated = table.auto_key and field in table.keys
        optional = update or generated or field.is_nullable or field.default_sql is not None or field.factory is not None
        annotation = _type(field)
        if update and field.kind in ('integer', 'real'):
            annotation += f' | _Increment[{_TYPES[field.kind]}]'
        arguments.append(f"{field.name}: {annotation} | Unset = UNSET" if optional else f"{field.name}: {annotation}")

    return arguments

def _values(table: Table, update: bool) -> str:
    fields = (field for field in table.fields if not update or (field not in table.keys and not field.is_immutable))

    return "{" + ", ".join(f"{field.name!r}: {field.name}" for field in fields) + "}"

def _compact_metadata(value: object) -> object:
    """Omit default metadata values to keep generated modules small."""
    if isinstance(value, dict):
        return {
            key: _compact_metadata(item)
            for key, item in value.items()
            if item not in (None, False, "", (), []) and not (key == "key" and item == value.get("name"))
        }

    if isinstance(value, (tuple, list)):
        return tuple(_compact_metadata(item) for item in value)

    return value

def render(schema: Schema) -> str:
    """Generate typed repositories; custom fields explicitly import their Python types."""
    normalized = schema.normalize()
    if not normalized.tables:
        raise SqrrlError("At least one table is required for generation")

    occupied = {name.lower() for table in normalized.tables for name in (table.model, f'{table.model}Key', f'{table.model}Repository', f'{table.model}Columns')}
    input_names: dict[str, str] = {}
    relation_names: dict[str, str] = {}
    for table in normalized.tables:
        for suffix, mapping in (('Create', input_names), ('Relations', relation_names)):
            name = f'{table.model}{suffix}'
            while name.lower() in occupied:
                name += 'Input' if suffix == 'Create' else 'Access'
            occupied.add(name.lower())
            mapping[table.name] = name

    kinds = sorted({field.kind for table in normalized.tables for field in table.fields})
    nullable = any(field.is_nullable for table in normalized.tables for field in table.fields)
    relationships = any(table.relationships for table in normalized.tables)
    decoders = [f"decode_{kind}" for kind in kinds if kind not in ('enum', 'custom', 'datetime', 'json')]
    if nullable:
        decoders.append("decode_nullable")

    imports = [
        "from sqlite3 import Row",
        'from typing import AsyncGenerator as _AsyncGenerator, Iterable as _Iterable, Optional, Optional as _Optional, cast as _cast' if any(k in kinds for k in ('enum', 'custom')) else 'from typing import AsyncGenerator as _AsyncGenerator, Iterable as _Iterable, Optional, Optional as _Optional',
        "from dataclasses import dataclass",
        "from contextlib import asynccontextmanager",
        "from sqrrl.schema import Schema",
        'from sqrrl.runtime import UNSET, UNSET as _UNSET, Column as _Column, Conflict as _Conflict, Database, Predicate, Repository, Unset, Unset as _Unset',
        "from sqrrl.runtime import " + ", ".join(decoders),
        "from builtins import " + ", ".join(f"{_TYPES[kind]} as _{_TYPES[kind]}" for kind in kinds if kind in ('integer', 'text', 'boolean', 'real', 'blob')),
    ]
    if relationships:
        imports.append('from sqrrl.runtime import UNLOADED as _UNLOADED, Related as _Related, Unloaded as _Unloaded')
        imports.append('from builtins import list as _list')
    if any(f.kind in ('integer', 'real') and f not in t.keys and not f.is_immutable for t in normalized.tables for f in t.fields):
        imports.append('from sqrrl.runtime import Increment as _Increment')
    if 'datetime' in kinds:
        imports.append('from datetime import datetime as _datetime')
        imports.append('from sqrrl.codecs import decode_datetime as _decode_datetime')
    if 'json' in kinds:
        imports.append('from sqrrl.codecs import JsonValue as _JsonValue')
        imports.append('from sqrrl.codecs import decode_json as _decode_json')
    references = {f.python_type for t in normalized.tables for f in t.fields if f.python_type is not None}
    if references:
        imports.append('from sqrrl.runtime import decode_field as _decode_field')
    for reference in sorted(references):
        module, _, symbol = reference.partition(':')
        imports.append(f'from {module} import {symbol} as {_python_alias(reference)}')
    lines = [
        _HEADER.rstrip(),
        "# fmt: off",
        *sorted(imports, key=lambda line: (len(line), line)),
        "",
    ]
    for table in normalized.tables:
        lines.extend(["", "@dataclass(frozen=True, slots=True, kw_only=True)", f"class {table.model}:"])
        lines.extend(f"    {field.name}: {_type(field, scoped=True)}" for field in table.fields)
        for relation in table.relationships:
            target = next(t for t in normalized.tables if t.name == relation.table)
            annotation = f'_list[_model_{target.model}]' if relation.many else f'_Optional[_model_{target.model}]'
            lines.append(f'    {relation.name}: {annotation} | _Unloaded = _UNLOADED')

        lines.extend(['', '', '@dataclass(frozen=True, slots=True, kw_only=True)', f'class {input_names[table.name]}:'])
        for field in table.fields:
            optional = (table.auto_key and field in table.keys) or field.is_nullable or field.default_sql is not None or field.factory is not None
            annotation = _type(field, scoped=True)
            suffix = ' | _Unset = _UNSET' if optional else ''
            lines.append(f'    {field.name}: {annotation}{suffix}')
        if len(table.keys) > 1:
            lines.extend(["", "", "@dataclass(frozen=True, slots=True, kw_only=True)", f"class {table.model}Key:"])
            lines.extend(f"    {field.name}: {_type(field, scoped=True)}" for field in table.keys)

    lines.extend(
            [
                "",
                "",
                "_SCHEMA = Schema.from_dict("
                + pformat(_compact_metadata(normalized.to_dict()), width=100, sort_dicts=True)
                + ")",
            ]
    )
    for index, table in enumerate(normalized.tables):
        lines.extend(["", "", f"def _decode_{table.name}(row: Row) -> {table.model}:", f"    return {table.model}("])
        for field in table.fields:
            decoder = f"decode_{field.kind}"
            if field.kind in ('datetime', 'json'):
                decoder = '_' + decoder
            value = (
                f"decode_nullable(row[{field.name!r}], {decoder})"
                if field.is_nullable
                else f"{decoder}(row[{field.name!r}])"
            )
            if field.kind in ('enum', 'custom'):
                value = f'_cast({_type(field)}, _decode_field(_SCHEMA.tables[{index}].field({field.name!r}), row[{field.name!r}]))'
            lines.append(f"        {field.name}={value},")

        lines.extend(
                [
                    "    )",
                    "",
                    "",
                    f"_model_{table.model} = {table.model}",
                    "",
                    "",
                    "@dataclass(frozen=True)",
                    f"class _{table.model}Columns:",
                ]
        )
        lines.extend(
                f"    {field.name}: _Column[_model_{table.model}, {_type(field, scoped=True)}] = _Column(_model_{table.model}, _SCHEMA.tables[{index}].field({field.name!r}))"
                for field in table.fields
        )
        lines.extend(
                [
                    "",
                    "",
                    f"{table.model}Columns = _{table.model}Columns()",
                    "",
                    "",
                    f"class {table.model}Repository(Repository[{table.model}]):",
                    "    def __init__(_self, database: Database) -> None:",
                    *(['        from builtins import super'] if any(t.model == 'super' for t in normalized.tables) else []),
                    f"        super().__init__(database, _SCHEMA.tables[{index}], {table.model}, _decode_{table.name})",
                ]
        )
        keys = table.keys
        if not keys:
            raise SqrrlError(f"{table.name} has no primary key")

        key_type = _type(keys[0]) if len(keys) == 1 else f"{table.model}Key"
        key = "(" + ", ".join(f"_key.{field.name}" for field in keys) + ",)" if len(keys) > 1 else "(_key,)"
        lines.extend(
                [
                    "",
                    f"    async def get(_self, _key: {key_type}, /) -> {table.model}:",
                    f"        return await _self._get({key})",
                ]
        )
        create_arguments = ", ".join(_arguments(table, False))
        lines.extend(
                [
                    "",
                    f"    async def create(_self, *, {create_arguments}) -> {table.model}:",
                    f"        return await _self._insert({_values(table, False)})",
                ]
        )
        values = '{' + ', '.join(f'{f.name!r}: _row.{f.name}' for f in table.fields) + '}'
        lines.extend([
            '',
            f'    async def insert(_self, _row: {input_names[table.name]}, /, *, conflict: Optional[_Conflict[{table.model}]] = None) -> Optional[{table.model}]:',
            f'        rows = await _self._insert_many(({values},), conflict)',
            '        return rows[0] if rows else None',
            '',
            f'    async def create_many(_self, _rows: _Iterable[{input_names[table.name]}], /, *, conflict: Optional[_Conflict[{table.model}]] = None) -> list[{table.model}]:',
            f'        return await _self._insert_many(({values} for _row in _rows), conflict)',
        ])
        update_arguments = _arguments(table, True)
        suffix = ", *, " + ", ".join(update_arguments) if update_arguments else ""
        lines.extend(
                [
                    "",
                    f"    async def update(_self, _key: {key_type}, /{suffix}) -> {table.model}:",
                    f"        return await _self._update({key}, {_values(table, True)})",
                ]
        )
        mutation_args = ', '.join(update_arguments)
        mutation_suffix = ', ' + mutation_args if mutation_args else ''
        lines.extend([
            '',
            f'    async def update_where(_self, _predicate: Optional[Predicate[{table.model}]] = None, /, *, _all_rows: bool = False{mutation_suffix}) -> int:',
            f'        return await _self._update_where(_predicate, {_values(table, True)}, all_rows=_all_rows)',
        ])
        lines.extend(
                ["", f"    async def delete(_self, _key: {key_type}, /) -> None:",
                 f"        await _self._delete({key})"]
        )

    for index, table in enumerate(normalized.tables):
        if not table.relationships:
            continue
        lines.extend(['', '', '@dataclass(frozen=True)', f'class _{table.model}Relations:'])
        for relation in table.relationships:
            target_index, target = next((i, t) for i, t in enumerate(normalized.tables) if t.name == relation.table)
            lines.append(
                f'    {relation.name}: _Related[{table.model}, {target.model}] = _Related({table.model}, {relation.name!r}, '
                f'_SCHEMA.tables[{index}], _SCHEMA.tables[{target_index}], {target.model}, _decode_{target.name}, '
                f'{relation.fields!r}, {relation.target!r}, {relation.many!r})'
            )
        lines.extend(['', f'{relation_names[table.name]} = _{table.model}Relations()'])

    lines.extend(
            [
                "",
                "",
                "class Client:",
                "    def __init__(self, database: Database) -> None:",
                "        self.database = database",
            ]
    )
    lines.extend(f"        self.{table.name} = {table.model}Repository(database)" for table in normalized.tables)
    lines.extend(
            [
                "",
                "    @asynccontextmanager",
                "    async def transaction(self) -> _AsyncGenerator[Client]:",
                "        async with self.database.transaction():",
                "            yield Client(self.database)",
                "",
            ]
    )
    source = "\n".join(lines)
    compile(source, "sqrrl_generated.py", "exec")

    return source

def write(path: str | Path, schema: Schema, *, check: bool = False) -> Path:
    target = Path(path)
    source = render(schema)
    try:
        existing: Optional[str] = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    if existing == source:
        return target

    if check:
        raise SqrrlError(f"{target} is missing or stale; run sqrrl generate")

    if existing is not None and not existing.startswith(_HEADER):
        raise SqrrlError(f"Refusing to overwrite handwritten file {target}")

    target.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile(
            mode="w", encoding="utf-8", newline="\n", dir=target.parent, suffix=".tmp", delete=False
    ) as temporary:
        temporary_path = Path(temporary.name)
        try:
            temporary.write(source)
        except BaseException:
            temporary.close()
            temporary_path.unlink(missing_ok=True)
            raise

    try:
        replace(temporary_path, target)
    finally:
        temporary_path.unlink(missing_ok=True)

    return target
