from pathlib import Path
from hashlib import sha256
from json import dumps, loads
from sqrrl.runtime import Database
from sqrrl.schema import Schema, quote
from aiosqlite import Connection, connect
from contextlib import asynccontextmanager
from dataclasses import dataclass, replace
from typing import Any, AsyncIterator, Optional
from sqrrl.errors import MigrationError, SchemaError
from sqlite3 import DatabaseError, complete_statement
from sqrrl.runtime import _cursor, _execute_sql, _settle
from re import DOTALL, compile as compile_pattern, fullmatch, match
from sqlite3 import (
    SQLITE_OK,
    SQLITE_DENY,
    SQLITE_ATTACH,
    SQLITE_DETACH,
    SQLITE_PRAGMA,
    SQLITE_FUNCTION,
    SQLITE_SAVEPOINT,
    SQLITE_TRANSACTION,
)

@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    parent: str
    before: str
    after: str
    schema: Schema
    statements: tuple[str, ...]
    checksum: str = ""
    format: int = 1

    def __post_init__(self) -> None:
        object.__setattr__(self, "statements", tuple(self.statements))

    @property
    def sql(self) -> str:
        return (
                "-- Generated by sqrrl. Review before applying; preserve migration history.\n\n"
                + "\n\n".join(self.statements)
                + "\n"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "format": self.format,
            "version": self.version,
            "name": self.name,
            "parent": self.parent,
            "before": self.before,
            "after": self.after,
            "schema": self.schema.to_dict(),
            "statements": list(self.statements),
            "checksum": self.checksum,
        }

@dataclass(frozen=True)
class Status:
    version: int
    name: str
    applied: bool

_LEDGER = 'CREATE TABLE "sqrrl_migrations" (version INTEGER PRIMARY KEY, name TEXT NOT NULL, checksum TEXT NOT NULL, fingerprint TEXT NOT NULL) STRICT'
_FORBIDDEN = {SQLITE_ATTACH, SQLITE_DETACH, SQLITE_PRAGMA, SQLITE_SAVEPOINT, SQLITE_TRANSACTION}
_SQL_TOKENS = compile_pattern(
        r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|`(?:``|[^`])*`|\[[^\]]*\]|--[^\n]*|/\*.*?\*/|;", DOTALL
)

def _digest(value: object) -> str:
    encoded = dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False)

    return sha256(encoded.encode("utf-8")).hexdigest()

def _checksum(migration: Migration) -> str:
    return _digest(migration.to_dict() | {"checksum": ""})

async def _objects(connection: Connection) -> list[tuple[str, str, str, str]]:
    async with _cursor(
            connection,
            "SELECT type, name, tbl_name, coalesce(sql, '') FROM main.sqlite_schema WHERE lower(substr(name, 1, 7)) != 'sqlite_' AND name != 'sqrrl_migrations' ORDER BY type, name",
    ) as cursor:
        return [(str(row[0]), str(row[1]), str(row[2]), str(row[3])) for row in await cursor.fetchall()]

async def _fingerprint(connection: Connection) -> str:
    return _digest(await _objects(connection))

def _validate(history: tuple[Migration, ...]) -> None:
    parent = ""
    before = _digest([])
    for version, migration in enumerate(history, 1):
        _validate_migration(migration)
        if migration.version != version:
            raise MigrationError("Invalid migration format, version, or name")

        if migration.parent != parent or migration.before != before or migration.checksum != _checksum(migration):
            raise MigrationError(f"Migration {version} has invalid ordering or checksum; history must remain unchanged")

        parent = migration.checksum
        before = migration.after

def _validate_migration(migration: Migration) -> None:
    if (
            type(migration.format) is not int
            or migration.format != 1
            or type(migration.version) is not int
            or migration.version < 1
    ):
        raise MigrationError("Invalid migration format or version")

    if not isinstance(migration.name, str) or not fullmatch(r"[a-z][a-z0-9_]*", migration.name):
        raise MigrationError("Invalid migration name")

    for value in (migration.before, migration.after, migration.checksum):
        if not isinstance(value, str) or not fullmatch(r"[0-9a-f]{64}", value):
            raise MigrationError("Invalid migration fingerprint or checksum")

    if not isinstance(migration.parent, str) or (migration.parent and not fullmatch(r"[0-9a-f]{64}", migration.parent)):
        raise MigrationError("Invalid migration parent checksum")

    if not isinstance(migration.schema, Schema):
        raise MigrationError("Invalid migration schema")

    if not migration.statements or any(
            not isinstance(statement, str) or not statement.strip() for statement in migration.statements
    ):
        raise MigrationError("Migration statements must be a nonempty sequence of SQL strings")

def _authorize(
        action: int, first: Optional[str], second: Optional[str], database: Optional[str], source: Optional[str]
) -> int:
    if action in _FORBIDDEN or (action == SQLITE_FUNCTION and second == "load_extension"):
        return SQLITE_DENY

    if first is not None and first.lower() == "sqrrl_migrations":
        return SQLITE_DENY

    return SQLITE_OK

def _split(script: str) -> tuple[str, ...]:
    statements = []
    start = 0
    for token in _SQL_TOKENS.finditer(script):
        if token.group() == ";" and complete_statement(script[start: token.end()]):
            statements.append(script[start: token.end()].strip())
            start = token.end()

    remainder = script[start:].strip()
    if remainder:
        statements.append(remainder)

    return tuple(statement for statement in statements if _leading_sql(statement))

def _leading_sql(statement: str) -> str:
    remaining = statement.lstrip(";\ufeff \t\r\n")
    while remaining.startswith(("--", "/*")):
        if remaining.startswith("--"):
            remaining = remaining.partition("\n")[2].lstrip(";\ufeff \t\r\n")
        else:
            _, separator, remaining = remaining.partition("*/")
            if not separator:
                raise MigrationError("Unterminated SQL comment")

            remaining = remaining.lstrip(";\ufeff \t\r\n")

    return remaining

async def _execute(connection: Connection, statements: tuple[str, ...]) -> None:
    try:
        await connection.set_authorizer(_authorize)
        for script in statements:
            for statement in _split(script):
                async with _cursor(connection, statement) as cursor:
                    while await cursor.fetchmany(256):
                        pass
    finally:
        await _settle(connection.set_authorizer(None))

async def _foreign_keys_valid(connection: Connection) -> None:
    async with _cursor(connection, "PRAGMA main.foreign_key_check") as cursor:
        if await cursor.fetchone() is not None:
            raise MigrationError("Migration would violate foreign key constraints")

async def _applied(connection: Connection, history: tuple[Migration, ...]) -> int:
    async with _cursor(connection, "SELECT sql FROM main.sqlite_schema WHERE name = 'sqrrl_migrations'") as cursor:
        ledger = await cursor.fetchone()

    if ledger is None:
        return 0

    if ledger[0] != _LEDGER:
        raise MigrationError("Migration ledger schema has changed")

    async with _cursor(
            connection, "SELECT version, name, checksum, fingerprint FROM main.sqrrl_migrations ORDER BY version"
    ) as cursor:
        rows = list(await cursor.fetchall())

    if len(rows) > len(history):
        raise MigrationError("Database history is newer than the supplied history")

    for row, migration in zip(rows, history):
        expected = (migration.version, migration.name, migration.checksum, migration.after)
        if tuple(row) != expected:
            raise MigrationError("Applied migration differs from supplied history")

    return len(rows)

@asynccontextmanager
async def _scratch() -> AsyncIterator[Database]:
    connection = connect(":memory:", isolation_level=None)
    try:
        await _settle(connection)
        await _execute_sql(connection, "PRAGMA foreign_keys = ON")
        yield Database(connection)
    finally:
        await _settle(connection.close())

async def _restore(connection: Connection, original: int, failed: bool) -> None:
    try:
        if failed and connection.in_transaction:
            await _execute_sql(connection, "ROLLBACK")

        await _execute_sql(connection, f"PRAGMA foreign_keys = {original}")
        async with _cursor(connection, "PRAGMA foreign_keys") as cursor:
            row = await cursor.fetchone()
            if row is None or row[0] != original:
                raise MigrationError("Foreign key enforcement was not restored")
    except BaseException as cleanup:
        await connection.close()
        raise MigrationError("Migration cleanup failed; the connection was closed") from cleanup

@asynccontextmanager
async def _migration_transaction(database: Database) -> AsyncIterator[Connection]:
    async with database._access():
        connection = database.connection
        if connection.in_transaction or connection.isolation_level is not None:
            raise MigrationError("Migrations require an idle connection in SQLite autocommit mode")

        async with _cursor(connection, "PRAGMA foreign_keys") as cursor:
            row = await cursor.fetchone()
            if row is None:
                raise MigrationError("Cannot read foreign key enforcement")

            original = int(row[0])

        failed = True
        try:
            await _execute_sql(connection, "PRAGMA foreign_keys = OFF")
            async with _cursor(connection, "PRAGMA foreign_keys") as cursor:
                row = await cursor.fetchone()
                if row is None or row[0] != 0:
                    raise MigrationError("Cannot disable foreign keys before rebuilding tables")

            await _execute_sql(connection, "BEGIN IMMEDIATE")
            yield connection
            await _execute_sql(connection, "COMMIT")
            failed = False
        finally:
            await _settle(_restore(connection, original, failed))

async def _record(connection: Connection, migration: Migration) -> None:
    await _execute_sql(
            connection,
            "INSERT INTO main.sqrrl_migrations(version, name, checksum, fingerprint) VALUES (?, ?, ?, ?)",
            (migration.version, migration.name, migration.checksum, migration.after),
    )

def _plan(previous: Schema, desired: Schema, allow_drop: bool) -> tuple[str, ...]:
    statements: list[str] = []
    index_drops: list[str] = []
    index_creates: list[str] = []
    old_tables = {table.key: table for table in previous.tables}
    for table in desired.tables:
        old = old_tables.pop(table.key, None)
        if old is None:
            statements.append(table.create_sql())
            index_creates.extend(table.index_sql())
            continue

        if table.create_sql() == old.create_sql():
            old_indexes = {index.name: sql for index, sql in zip(old.indexes, old.index_sql(), strict=True)}
            new_indexes = {index.name: sql for index, sql in zip(table.indexes, table.index_sql(), strict=True)}
            index_drops.extend(
                    f"DROP INDEX main.{quote(name)};" for name, sql in old_indexes.items() if
                    new_indexes.get(name) != sql
            )
            index_creates.extend(sql for name, sql in new_indexes.items() if old_indexes.get(name) != sql)
            continue

        if tuple(field.key for field in old.keys) != tuple(field.key for field in table.keys):
            raise MigrationError(f"{table.name}: automatic primary key changes are unsupported")

        old_fields = {field.key: field for field in old.fields}
        source = []
        destination = []
        for field in table.fields:
            prior = old_fields.pop(field.key, None)
            if prior is None:
                if not field.is_nullable and field.default_sql is None:
                    raise MigrationError(f"{table.name}.{field.name} needs a default or a staged backfill")
                continue

            if field.kind != prior.kind:
                raise MigrationError(f"{table.name}.{field.name}: automatic representation changes are unsupported")

            source.append(quote(prior.name))
            destination.append(quote(field.name))

        if old_fields and not allow_drop:
            raise MigrationError(f"{table.name} removes fields; preserve identity() for renames or pass --allow-drop")

        if not source:
            raise MigrationError(f"{table.name} has no preserved fields")

        temporary = "sqrrl_rebuild_" + table.name
        statements.extend(
                (
                    table.create_sql(temporary),
                    f"INSERT INTO main.{quote(temporary)} ({', '.join(destination)}) SELECT {', '.join(source)} FROM main.{quote(old.name)};",
                    f"DROP TABLE main.{quote(old.name)};",
                    f"ALTER TABLE main.{quote(temporary)} RENAME TO {quote(table.name)};",
                )
        )
        index_creates.extend(table.index_sql())

    if old_tables and not allow_drop:
        raise MigrationError("Schema removes tables; preserve their key for renames or pass --allow-drop")

    statements.extend(
            f"DROP TABLE main.{quote(table.name)};" for table in
            sorted(old_tables.values(), key=lambda table: table.name)
    )

    return tuple(index_drops + statements + index_creates)

def _new(
        history: tuple[Migration, ...], schema: Schema, name: str, statements: tuple[str, ...], before: str, after: str
) -> Migration:
    if not fullmatch(r"[a-z][a-z0-9_]*", name):
        raise MigrationError(
                "Migration names must start with a lowercase letter and use letters, digits, or underscores"
        )

    migration = Migration(
            len(history) + 1, name, history[-1].checksum if history else "", before, after, schema, statements
    )

    return replace(migration, checksum=_checksum(migration))

def load(directory: str | Path) -> tuple[Migration, ...]:
    path = Path(directory)
    try:
        entries = tuple(path.iterdir())
    except FileNotFoundError:
        return ()
    except OSError as error:
        raise MigrationError(f"Cannot read migration directory {path}: {error}") from error

    history = []
    expected = set()
    for metadata in sorted(entry for entry in entries if entry.suffix.lower() == ".json"):
        try:
            data = loads(metadata.read_text(encoding="utf-8"))
            data["schema"] = Schema.from_dict(data["schema"])
            data["statements"] = tuple(data["statements"])
            migration = Migration(**data)
            _validate_migration(migration)
            base = f"{migration.version:06d}_{migration.name}"
            if metadata.name != base + ".json":
                raise MigrationError("Unexpected migration metadata filename")

            sql_name = base + ".sql"
            if (path / sql_name).read_text(encoding="utf-8") != migration.sql:
                raise MigrationError("SQL differs from migration metadata; create a new migration to change history")

            expected.add(sql_name)
            history.append(migration)
        except (ValueError, TypeError, KeyError, AttributeError, OSError, SchemaError) as error:
            raise MigrationError(f"Cannot load {metadata.name}: {error}") from error

    if {entry.name for entry in entries if entry.suffix.lower() == ".sql"} != expected:
        raise MigrationError("Migration SQL has no matching metadata")

    result = tuple(sorted(history, key=lambda migration: migration.version))
    _validate(result)

    return result

def write(directory: str | Path, migration: Migration) -> Path:
    _validate_migration(migration)
    if migration.checksum != _checksum(migration):
        raise MigrationError("Cannot write invalid migration metadata")

    path = Path(directory)
    path.mkdir(parents=True, exist_ok=True)
    base = f"{migration.version:06d}_{migration.name}"
    created = []
    try:
        for suffix, content in (
                (".sql", migration.sql),
                (".json", dumps(migration.to_dict(), indent=2, sort_keys=True) + "\n"),
        ):
            target = path / (base + suffix)
            with target.open("x", encoding="utf-8", newline="\n") as output:
                created.append(target)
                output.write(content)
    except BaseException:
        for target in created:
            target.unlink(missing_ok=True)
        raise

    return path / (base + ".sql")

async def apply(database: Database, history: tuple[Migration, ...]) -> None:
    """Apply all pending migrations and ledger records as one atomic batch."""
    _validate(history)
    try:
        async with _migration_transaction(database) as connection:
            count = await _applied(connection, history)
            expected = history[count - 1].after if count else _digest([])
            if await _fingerprint(connection) != expected:
                raise MigrationError("Live schema drift detected; refusing to modify the database")

            await _execute_sql(connection, _LEDGER.replace('CREATE TABLE "', 'CREATE TABLE IF NOT EXISTS main."', 1))
            for migration in history[count:]:
                await _execute(connection, migration.statements)
                await _foreign_keys_valid(connection)
                if await _fingerprint(connection) != migration.after:
                    raise MigrationError(f"Migration {migration.version} did not produce the expected schema")

                await _record(connection, migration)
    except DatabaseError as error:
        raise MigrationError(f"Migration failed: {error}") from error

async def diff(
        history: tuple[Migration, ...], schema: Schema, name: str, *, allow_drop: bool = False
) -> Optional[Migration]:
    if not fullmatch(r"[a-z][a-z0-9_]*", name):
        raise MigrationError(
                "Migration names must start with a lowercase letter and use letters, digits, or underscores"
        )

    desired = schema.normalize()
    _validate(history)
    previous = history[-1].schema if history else Schema(())
    statements = _plan(previous, desired, allow_drop)
    async with _scratch() as replay, _scratch() as expected:
        await apply(replay, history)
        for table in desired.tables:
            await _execute_sql(expected.connection, table.create_sql())
            for statement in table.index_sql():
                await _execute_sql(expected.connection, statement)

        if not statements:
            return None

        before = await _fingerprint(replay.connection)
        async with _migration_transaction(replay) as connection:
            await _execute(connection, statements)
            await _foreign_keys_valid(connection)

        after = await _fingerprint(replay.connection)
        if after != await _fingerprint(expected.connection):
            raise MigrationError("Candidate migration does not reproduce the declared schema")

        migration = _new(history, desired, name, statements, before, after)

    async with _scratch() as replay:
        await apply(replay, history + (migration,))

    return migration

async def check(history: tuple[Migration, ...], schema: Schema) -> None:
    if await diff(history, schema, "check") is not None:
        raise MigrationError("Schema changes have no migration; run sqrrl migrate diff NAME")

async def status(database: Database, history: tuple[Migration, ...]) -> tuple[Status, ...]:
    """Inspect history and drift without creating a ledger."""
    _validate(history)
    async with database.transaction():
        count = await _applied(database.connection, history)
        expected = history[count - 1].after if count else _digest([])
        if await _fingerprint(database.connection) != expected:
            raise MigrationError("Live schema drift detected")

    return tuple(Status(migration.version, migration.name, index < count) for index, migration in enumerate(history))

async def baseline(database: Database, history: tuple[Migration, ...], version: int) -> None:
    """Adopt an exact schema match. Equivalent but differently written DDL is rejected."""
    _validate(history)
    if type(version) is not int or not 1 <= version <= len(history):
        raise MigrationError("Baseline version is outside the supplied history")

    async with _scratch() as replay:
        await apply(replay, history[:version])

    async with _migration_transaction(database) as connection:
        count = await _applied(connection, history)
        if count not in (0, version):
            raise MigrationError("Baseline version conflicts with existing migration history")

        if await _fingerprint(connection) != history[version - 1].after:
            raise MigrationError("Baseline requires an exact schema match with the selected migration")

        await _foreign_keys_valid(connection)
        if count == version:
            return

        await _execute_sql(connection, _LEDGER.replace('CREATE TABLE "', 'CREATE TABLE IF NOT EXISTS main."', 1))
        for migration in history[:version]:
            await _record(connection, migration)

async def custom(history: tuple[Migration, ...], name: str, sql: str) -> Migration:
    """Record a data-only SQL backfill. Custom schema objects are not supported yet."""
    _validate(history)
    statements = _split(sql)
    if not statements:
        raise MigrationError("Custom migration is empty")

    for statement in statements:
        keyword = match(r"[A-Za-z]+", _leading_sql(statement))
        first = keyword.group().upper() if keyword else ""
        if first not in ("INSERT", "UPDATE", "DELETE", "REPLACE", "SELECT", "WITH"):
            raise MigrationError("Custom migrations currently accept data statements only")

    schema = history[-1].schema if history else Schema(())
    async with _scratch() as replay:
        await apply(replay, history)
        before = await _fingerprint(replay.connection)
        async with _migration_transaction(replay) as connection:
            await _execute(connection, statements)
            await _foreign_keys_valid(connection)

        if await _fingerprint(replay.connection) != before or await _applied(replay.connection, history) != len(
                history
        ):
            raise MigrationError("Custom migration changed schema or migration history")

        migration = _new(history, schema, name, statements, before, before)

    async with _scratch() as replay:
        await apply(replay, history + (migration,))

    return migration
