from hashlib import sha256
from sqrrl.errors import SchemaError
from sqrrl.schema import Field, Table, quote


_STORAGE = {
    'integer': 'BIGINT',
    'boolean': 'SMALLINT',
    'real': 'DOUBLE PRECISION',
    'text': 'TEXT',
    'blob': 'BYTEA',
    'datetime': 'TEXT',
    'json': 'TEXT',
    'enum': 'TEXT',
    'custom': 'BYTEA',
}


def default_sql(field: Field) -> str:
    value = field.default_sql or 'NULL'
    if value[:2].lower() == "x'":
        return 'decode(' + value[1:] + ", 'hex')"
    return value


def column_sql(table: Table, field: Field) -> str:
    column = f'{quote(field.name)} {_STORAGE[field.kind]}'
    if table.auto_key and field in table.keys:
        if field.default_sql is not None:
            raise SchemaError('PostgreSQL identity keys cannot also have a SQL default')
        column += ' GENERATED BY DEFAULT AS IDENTITY'
    elif field.default_sql is not None:
        column += f' DEFAULT {default_sql(field)}'
    if not field.is_nullable:
        column += ' NOT NULL'
    return column


def constraints(table: Table, *, foreign: bool = False) -> dict[str, str]:
    result = {}

    def add(key: str, sql: str) -> None:
        name = 'sqrrl_c_' + sha256(((table.key or table.name) + ':' + key).encode()).hexdigest()[:24]
        result[name] = sql

    if foreign:
        references = table.foreign_keys + tuple(f.reference for f in table.fields if f.reference is not None)
        for index, reference in enumerate(references):
            source = ', '.join(map(quote, reference.fields))
            target = ', '.join(map(quote, reference.target))
            add(
                f'fk:{index}',
                f'FOREIGN KEY ({source}) REFERENCES {quote(reference.table)} ({target}) ON DELETE {reference.on_delete}',
            )
    else:
        add('pk', 'PRIMARY KEY (' + ', '.join(quote(f.name) for f in table.keys) + ')')
        for field in table.fields:
            if field.is_unique:
                add('unique:' + (field.key or field.name), f'UNIQUE ({quote(field.name)})')
            if field.kind == 'boolean':
                add('bool:' + (field.key or field.name), f'CHECK ({quote(field.name)} IN (0, 1))')
        for check in table.checks:
            if check.name in result:
                raise SchemaError(
                    f'{table.name}: check constraint name conflicts with a generated constraint: {check.name}'
                )
            result[check.name] = f'CHECK ({check.expression})'
    return result


def create_sql(table: Table, *, foreign: bool = True) -> str:
    if table.non_strict:
        raise SchemaError('PostgreSQL tables are always typed; non_strict is SQLite-only')
    for name in (
        table.name,
        *(f.name for f in table.fields),
        *(i.name for i in table.indexes),
        *(c.name for c in table.checks),
    ):
        if len(name.encode()) > 63:
            raise SchemaError(f'PostgreSQL identifier exceeds 63 bytes: {name}')
    parts = [column_sql(table, field) for field in table.fields]
    checks = constraints(table)
    if foreign:
        checks.update(constraints(table, foreign=True))
    parts.extend(f'CONSTRAINT {quote(name)} {sql}' for name, sql in checks.items())
    return f'CREATE TABLE {quote(table.name)} (\n  ' + ',\n  '.join(parts) + '\n);'


def index_sql(table: Table) -> tuple[str, ...]:
    return tuple(
        f'CREATE {"UNIQUE " if index.unique else ""}INDEX {quote(index.name)} ON {quote(table.name)} '
        f'({", ".join(map(quote, index.fields))})' + (f' WHERE {index.where}' if index.where else '') + ';'
        for index in table.indexes
    )
