# Code generated by sqrrl. DO NOT EDIT.
# fmt: off
from sqlite3 import Row
from sqrrl.schema import Schema
from dataclasses import dataclass
from builtins import list as _list
from contextlib import asynccontextmanager
from datetime import datetime as _datetime
from builtins import int as _int, str as _str
from sqrrl.codecs import JsonValue as _JsonValue
from sqrrl.runtime import Increment as _Increment
from sqrrl.codecs import decode_json as _decode_json
from sqrrl.runtime import decode_field as _decode_field
from sqrrl.codecs import decode_datetime as _decode_datetime
from sqrrl.runtime import decode_integer, decode_text, decode_nullable
from examples.library_types import Label as _type_examples_dlibrary_utypes_cLabel
from examples.library_types import Binding as _type_examples_dlibrary_utypes_cBinding
from sqrrl.runtime import UNLOADED as _UNLOADED, Related as _Related, Unloaded as _Unloaded
from typing import AsyncGenerator as _AsyncGenerator, Iterable as _Iterable, Optional, Optional as _Optional, cast as _cast
from sqrrl.runtime import UNSET, UNSET as _UNSET, Column as _Column, Conflict as _Conflict, Database, Predicate, Repository, Unset, Unset as _Unset


@dataclass(frozen=True, slots=True, kw_only=True)
class Book:
    id: _int
    isbn: _str
    title: _str
    room: _Optional[_str]
    shelf: _Optional[_int]
    copies: _int
    created: _datetime
    edited: _Optional[_datetime]
    metadata: _JsonValue
    binding: _type_examples_dlibrary_utypes_cBinding
    label: _Optional[_type_examples_dlibrary_utypes_cLabel]
    location: _Optional[_model_Shelf] | _Unloaded = _UNLOADED


@dataclass(frozen=True, slots=True, kw_only=True)
class BookCreate:
    id: _int | _Unset = _UNSET
    isbn: _str
    title: _str
    room: _Optional[_str] | _Unset = _UNSET
    shelf: _Optional[_int] | _Unset = _UNSET
    copies: _int | _Unset = _UNSET
    created: _datetime | _Unset = _UNSET
    edited: _Optional[_datetime] | _Unset = _UNSET
    metadata: _JsonValue | _Unset = _UNSET
    binding: _type_examples_dlibrary_utypes_cBinding | _Unset = _UNSET
    label: _Optional[_type_examples_dlibrary_utypes_cLabel] | _Unset = _UNSET

@dataclass(frozen=True, slots=True, kw_only=True)
class Shelf:
    room: _str
    number: _int
    name: _str
    books: _list[_model_Book] | _Unloaded = _UNLOADED
    sign: _Optional[_model_Sign] | _Unloaded = _UNLOADED


@dataclass(frozen=True, slots=True, kw_only=True)
class ShelfCreate:
    room: _str
    number: _int
    name: _str


@dataclass(frozen=True, slots=True, kw_only=True)
class ShelfKey:
    room: _str
    number: _int

@dataclass(frozen=True, slots=True, kw_only=True)
class Sign:
    id: _int
    room: _str
    shelf: _int
    caption: _str


@dataclass(frozen=True, slots=True, kw_only=True)
class SignCreate:
    id: _int | _Unset = _UNSET
    room: _str
    shelf: _int
    caption: _str


_SCHEMA = Schema.from_dict({'tables': ({'fields': ({'is_primary': True, 'kind': 'integer', 'name': 'id'},
                        {'is_immutable': True, 'is_unique': True, 'kind': 'text', 'name': 'isbn'},
                        {'kind': 'text', 'name': 'title'},
                        {'is_nullable': True, 'kind': 'text', 'name': 'room'},
                        {'is_nullable': True, 'kind': 'integer', 'name': 'shelf'},
                        {'default_sql': '0', 'kind': 'integer', 'name': 'copies'},
                        {'factory': 'examples.library_types:utc_now',
                         'is_immutable': True,
                         'kind': 'datetime',
                         'name': 'created'},
                        {'is_nullable': True,
                         'kind': 'datetime',
                         'name': 'edited',
                         'update_factory': 'examples.library_types:utc_now'},
                        {'factory': 'examples.library_types:empty_metadata',
                         'kind': 'json',
                         'name': 'metadata'},
                        {'default_sql': "'PAPER'",
                         'kind': 'enum',
                         'name': 'binding',
                         'python_type': 'examples.library_types:Binding'},
                        {'codec': 'examples.library_types:label_codec',
                         'is_nullable': True,
                         'kind': 'custom',
                         'name': 'label',
                         'python_type': 'examples.library_types:Label'}),
             'foreign_keys': ({'fields': ('room', 'shelf'),
                               'on_delete': 'NO ACTION',
                               'table': 'shelves',
                               'target': ('room', 'number')},),
             'model': 'Book',
             'name': 'books',
             'relationships': ({'fields': ('room', 'shelf'),
                                'name': 'location',
                                'table': 'shelves',
                                'target': ('room', 'number')},)},
            {'fields': ({'kind': 'text', 'name': 'room'},
                        {'kind': 'integer', 'name': 'number'},
                        {'kind': 'text', 'name': 'name'}),
             'model': 'Shelf',
             'name': 'shelves',
             'primary_key': ('room', 'number'),
             'relationships': ({'fields': ('room', 'number'),
                                'many': True,
                                'name': 'books',
                                'table': 'books',
                                'target': ('room', 'shelf')},
                               {'fields': ('room', 'number'),
                                'name': 'sign',
                                'table': 'signs',
                                'target': ('room', 'shelf')})},
            {'fields': ({'is_primary': True, 'kind': 'integer', 'name': 'id'},
                        {'kind': 'text', 'name': 'room'},
                        {'kind': 'integer', 'name': 'shelf'},
                        {'kind': 'text', 'name': 'caption'}),
             'foreign_keys': ({'fields': ('room', 'shelf'),
                               'on_delete': 'NO ACTION',
                               'table': 'shelves',
                               'target': ('room', 'number')},),
             'indexes': ({'fields': ('room', 'shelf'), 'name': 'sign_location', 'unique': True},),
             'model': 'Sign',
             'name': 'signs'})})


def _decode_books(row: Row) -> Book:
    return Book(
        id=decode_integer(row['id']),
        isbn=decode_text(row['isbn']),
        title=decode_text(row['title']),
        room=decode_nullable(row['room'], decode_text),
        shelf=decode_nullable(row['shelf'], decode_integer),
        copies=decode_integer(row['copies']),
        created=_decode_datetime(row['created']),
        edited=decode_nullable(row['edited'], _decode_datetime),
        metadata=_decode_json(row['metadata']),
        binding=_cast(_type_examples_dlibrary_utypes_cBinding, _decode_field(_SCHEMA.tables[0].field('binding'), row['binding'])),
        label=_cast(Optional[_type_examples_dlibrary_utypes_cLabel], _decode_field(_SCHEMA.tables[0].field('label'), row['label'])),
    )


_model_Book = Book


@dataclass(frozen=True)
class _BookColumns:
    id: _Column[_model_Book, _int] = _Column(_model_Book, _SCHEMA.tables[0].field('id'))
    isbn: _Column[_model_Book, _str] = _Column(_model_Book, _SCHEMA.tables[0].field('isbn'))
    title: _Column[_model_Book, _str] = _Column(_model_Book, _SCHEMA.tables[0].field('title'))
    room: _Column[_model_Book, _Optional[_str]] = _Column(_model_Book, _SCHEMA.tables[0].field('room'))
    shelf: _Column[_model_Book, _Optional[_int]] = _Column(_model_Book, _SCHEMA.tables[0].field('shelf'))
    copies: _Column[_model_Book, _int] = _Column(_model_Book, _SCHEMA.tables[0].field('copies'))
    created: _Column[_model_Book, _datetime] = _Column(_model_Book, _SCHEMA.tables[0].field('created'))
    edited: _Column[_model_Book, _Optional[_datetime]] = _Column(_model_Book, _SCHEMA.tables[0].field('edited'))
    metadata: _Column[_model_Book, _JsonValue] = _Column(_model_Book, _SCHEMA.tables[0].field('metadata'))
    binding: _Column[_model_Book, _type_examples_dlibrary_utypes_cBinding] = _Column(_model_Book, _SCHEMA.tables[0].field('binding'))
    label: _Column[_model_Book, _Optional[_type_examples_dlibrary_utypes_cLabel]] = _Column(_model_Book, _SCHEMA.tables[0].field('label'))


BookColumns = _BookColumns()


class BookRepository(Repository[Book]):
    def __init__(_self, database: Database) -> None:
        super().__init__(database, _SCHEMA.tables[0], Book, _decode_books)

    async def get(_self, _key: int, /) -> Book:
        return await _self._get((_key,))

    async def create(_self, *, id: int | Unset = UNSET, isbn: str, title: str, room: Optional[str] | Unset = UNSET, shelf: Optional[int] | Unset = UNSET, copies: int | Unset = UNSET, created: _datetime | Unset = UNSET, edited: Optional[_datetime] | Unset = UNSET, metadata: _JsonValue | Unset = UNSET, binding: _type_examples_dlibrary_utypes_cBinding | Unset = UNSET, label: Optional[_type_examples_dlibrary_utypes_cLabel] | Unset = UNSET) -> Book:
        return await _self._insert({'id': id, 'isbn': isbn, 'title': title, 'room': room, 'shelf': shelf, 'copies': copies, 'created': created, 'edited': edited, 'metadata': metadata, 'binding': binding, 'label': label})

    async def insert(_self, _row: BookCreate, /, *, conflict: Optional[_Conflict[Book]] = None) -> Optional[Book]:
        rows = await _self._insert_many(({'id': _row.id, 'isbn': _row.isbn, 'title': _row.title, 'room': _row.room, 'shelf': _row.shelf, 'copies': _row.copies, 'created': _row.created, 'edited': _row.edited, 'metadata': _row.metadata, 'binding': _row.binding, 'label': _row.label},), conflict)
        return rows[0] if rows else None

    async def create_many(_self, _rows: _Iterable[BookCreate], /, *, conflict: Optional[_Conflict[Book]] = None) -> list[Book]:
        return await _self._insert_many(({'id': _row.id, 'isbn': _row.isbn, 'title': _row.title, 'room': _row.room, 'shelf': _row.shelf, 'copies': _row.copies, 'created': _row.created, 'edited': _row.edited, 'metadata': _row.metadata, 'binding': _row.binding, 'label': _row.label} for _row in _rows), conflict)

    async def update(_self, _key: int, /, *, title: str | Unset = UNSET, room: Optional[str] | Unset = UNSET, shelf: Optional[int] | _Increment[int] | Unset = UNSET, copies: int | _Increment[int] | Unset = UNSET, edited: Optional[_datetime] | Unset = UNSET, metadata: _JsonValue | Unset = UNSET, binding: _type_examples_dlibrary_utypes_cBinding | Unset = UNSET, label: Optional[_type_examples_dlibrary_utypes_cLabel] | Unset = UNSET) -> Book:
        return await _self._update((_key,), {'title': title, 'room': room, 'shelf': shelf, 'copies': copies, 'edited': edited, 'metadata': metadata, 'binding': binding, 'label': label})

    async def update_where(_self, _predicate: Optional[Predicate[Book]] = None, /, *, _all_rows: bool = False, title: str | Unset = UNSET, room: Optional[str] | Unset = UNSET, shelf: Optional[int] | _Increment[int] | Unset = UNSET, copies: int | _Increment[int] | Unset = UNSET, edited: Optional[_datetime] | Unset = UNSET, metadata: _JsonValue | Unset = UNSET, binding: _type_examples_dlibrary_utypes_cBinding | Unset = UNSET, label: Optional[_type_examples_dlibrary_utypes_cLabel] | Unset = UNSET) -> int:
        return await _self._update_where(_predicate, {'title': title, 'room': room, 'shelf': shelf, 'copies': copies, 'edited': edited, 'metadata': metadata, 'binding': binding, 'label': label}, all_rows=_all_rows)

    async def delete(_self, _key: int, /) -> None:
        await _self._delete((_key,))


def _decode_shelves(row: Row) -> Shelf:
    return Shelf(
        room=decode_text(row['room']),
        number=decode_integer(row['number']),
        name=decode_text(row['name']),
    )


_model_Shelf = Shelf


@dataclass(frozen=True)
class _ShelfColumns:
    room: _Column[_model_Shelf, _str] = _Column(_model_Shelf, _SCHEMA.tables[1].field('room'))
    number: _Column[_model_Shelf, _int] = _Column(_model_Shelf, _SCHEMA.tables[1].field('number'))
    name: _Column[_model_Shelf, _str] = _Column(_model_Shelf, _SCHEMA.tables[1].field('name'))


ShelfColumns = _ShelfColumns()


class ShelfRepository(Repository[Shelf]):
    def __init__(_self, database: Database) -> None:
        super().__init__(database, _SCHEMA.tables[1], Shelf, _decode_shelves)

    async def get(_self, _key: ShelfKey, /) -> Shelf:
        return await _self._get((_key.room, _key.number,))

    async def create(_self, *, room: str, number: int, name: str) -> Shelf:
        return await _self._insert({'room': room, 'number': number, 'name': name})

    async def insert(_self, _row: ShelfCreate, /, *, conflict: Optional[_Conflict[Shelf]] = None) -> Optional[Shelf]:
        rows = await _self._insert_many(({'room': _row.room, 'number': _row.number, 'name': _row.name},), conflict)
        return rows[0] if rows else None

    async def create_many(_self, _rows: _Iterable[ShelfCreate], /, *, conflict: Optional[_Conflict[Shelf]] = None) -> list[Shelf]:
        return await _self._insert_many(({'room': _row.room, 'number': _row.number, 'name': _row.name} for _row in _rows), conflict)

    async def update(_self, _key: ShelfKey, /, *, name: str | Unset = UNSET) -> Shelf:
        return await _self._update((_key.room, _key.number,), {'name': name})

    async def update_where(_self, _predicate: Optional[Predicate[Shelf]] = None, /, *, _all_rows: bool = False, name: str | Unset = UNSET) -> int:
        return await _self._update_where(_predicate, {'name': name}, all_rows=_all_rows)

    async def delete(_self, _key: ShelfKey, /) -> None:
        await _self._delete((_key.room, _key.number,))


def _decode_signs(row: Row) -> Sign:
    return Sign(
        id=decode_integer(row['id']),
        room=decode_text(row['room']),
        shelf=decode_integer(row['shelf']),
        caption=decode_text(row['caption']),
    )


_model_Sign = Sign


@dataclass(frozen=True)
class _SignColumns:
    id: _Column[_model_Sign, _int] = _Column(_model_Sign, _SCHEMA.tables[2].field('id'))
    room: _Column[_model_Sign, _str] = _Column(_model_Sign, _SCHEMA.tables[2].field('room'))
    shelf: _Column[_model_Sign, _int] = _Column(_model_Sign, _SCHEMA.tables[2].field('shelf'))
    caption: _Column[_model_Sign, _str] = _Column(_model_Sign, _SCHEMA.tables[2].field('caption'))


SignColumns = _SignColumns()


class SignRepository(Repository[Sign]):
    def __init__(_self, database: Database) -> None:
        super().__init__(database, _SCHEMA.tables[2], Sign, _decode_signs)

    async def get(_self, _key: int, /) -> Sign:
        return await _self._get((_key,))

    async def create(_self, *, id: int | Unset = UNSET, room: str, shelf: int, caption: str) -> Sign:
        return await _self._insert({'id': id, 'room': room, 'shelf': shelf, 'caption': caption})

    async def insert(_self, _row: SignCreate, /, *, conflict: Optional[_Conflict[Sign]] = None) -> Optional[Sign]:
        rows = await _self._insert_many(({'id': _row.id, 'room': _row.room, 'shelf': _row.shelf, 'caption': _row.caption},), conflict)
        return rows[0] if rows else None

    async def create_many(_self, _rows: _Iterable[SignCreate], /, *, conflict: Optional[_Conflict[Sign]] = None) -> list[Sign]:
        return await _self._insert_many(({'id': _row.id, 'room': _row.room, 'shelf': _row.shelf, 'caption': _row.caption} for _row in _rows), conflict)

    async def update(_self, _key: int, /, *, room: str | Unset = UNSET, shelf: int | _Increment[int] | Unset = UNSET, caption: str | Unset = UNSET) -> Sign:
        return await _self._update((_key,), {'room': room, 'shelf': shelf, 'caption': caption})

    async def update_where(_self, _predicate: Optional[Predicate[Sign]] = None, /, *, _all_rows: bool = False, room: str | Unset = UNSET, shelf: int | _Increment[int] | Unset = UNSET, caption: str | Unset = UNSET) -> int:
        return await _self._update_where(_predicate, {'room': room, 'shelf': shelf, 'caption': caption}, all_rows=_all_rows)

    async def delete(_self, _key: int, /) -> None:
        await _self._delete((_key,))


@dataclass(frozen=True)
class _BookRelations:
    location: _Related[Book, Shelf] = _Related(Book, 'location', _SCHEMA.tables[0], _SCHEMA.tables[1], Shelf, _decode_shelves, ('room', 'shelf'), ('room', 'number'), False)

BookRelations = _BookRelations()


@dataclass(frozen=True)
class _ShelfRelations:
    books: _Related[Shelf, Book] = _Related(Shelf, 'books', _SCHEMA.tables[1], _SCHEMA.tables[0], Book, _decode_books, ('room', 'number'), ('room', 'shelf'), True)
    sign: _Related[Shelf, Sign] = _Related(Shelf, 'sign', _SCHEMA.tables[1], _SCHEMA.tables[2], Sign, _decode_signs, ('room', 'number'), ('room', 'shelf'), False)

ShelfRelations = _ShelfRelations()


class Client:
    def __init__(self, database: Database) -> None:
        self.database = database
        self.books = BookRepository(database)
        self.shelves = ShelfRepository(database)
        self.signs = SignRepository(database)

    @asynccontextmanager
    async def transaction(self) -> _AsyncGenerator[Client]:
        async with self.database.transaction():
            yield Client(self.database)
